name = "OceanWaveSpectralFitting"
uuid = "a44e4c57-a566-426a-9563-b0c20c24dda1"
authors = ["Jake Grainger <j.p.grainger2@outlook.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"

[compat]
julia = "1"

[targets]
test = ["Test","FiniteDifferences"]
